import Head from "next/head";
import Footer from "../../components/Footer";
import Grid from "../../components/Grid";
import Header from "../../components/Header";
import Social from "../../components/Social";
import styles from "../../styles/pages/blog.module.scss";

import fs from "fs";
import matter from "gray-matter";
import path from "path";

import Link from "next/link";
import { prettyDate } from "../../helpers/prettyDate";

type Post = {
  slug: string;
  frontmatter: {
    title: string;
    date: string;
    description: string;
  };
};

export default function Blog({ posts }: { posts: Post[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Grid>
          <div className={styles.blockSpacing}>
            <h1>Blog</h1>
            <p className={styles.description}>
              My mad ramblings about the world of web development, tech and
              other things I find vaguely interesting. I also cross post my blog
              posts to{" "}
              <a
                href="https://dev.to/kieranmv95"
                target="_blank"
                rel="noreferrer"
              >
                dev.to
              </a>
            </p>

            <ul className={styles.blogPostsList}>
              {posts.map((post, index) => (
                <li key={post.slug}>
                  <Link href={`blog/${post.slug}`}>
                    <span>{prettyDate(new Date(post.frontmatter.date))}</span>{" "}
                    {post.frontmatter.title}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </Grid>
        <Footer />
        <Social />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const postsDirectory = path.join(process.cwd(), "blog");
  const files = fs.readdirSync(postsDirectory, "utf-8");

  const posts = files.map((filename) => {
    const slug = filename.replace(".md", "");
    const readFile = fs.readFileSync(`${postsDirectory}/${filename}`, "utf-8");
    const { data: frontmatter } = matter(readFile);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
}
