import Head from "next/head";
import Footer from "../components/Footer";
import Grid from "../components/Grid";
import Header from "../components/Header";
import Social from "../components/Social";
import styles from "../styles/pages/about.module.css";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Grid>
          <div className={styles.blockSpacing}>
            <h1>About Me</h1>
            <p className={styles.description}>
              I&apos;m a self taught Developer based in Manchester, UK. I work
              building digital products for both businesses and consumer use.
              I&apos;m confident, naturally curious, and improving on my skills
              day by day.
            </p>
          </div>
        </Grid>
        <Grid>
          <div className={styles.blockSpacing}>
            <h2>Coming Soon</h2>
            <p>
              I&apos;m currently finishing development on this page so watch
              this space
            </p>
          </div>
        </Grid>
        <Footer />
        <Social />
      </main>
    </>
  );
}
