import Head from "next/head";
import Link from "next/link";
import Footer from "../components/Footer";
import Grid from "../components/Grid";
import Header from "../components/Header";
import Social from "../components/Social";
import styles from "../styles/pages/home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className={styles.content}>
          <div>
            <p className={styles.intro}>Hi I'm</p>
            <h1>KIERAN VENISON</h1>
            <p className={styles.description}>
              I'm a self taught Developer based in Manchester, UK. I work
              building digital products for both businesses and consumer use.
              I'm confident, naturally curious, and improving on my skills day
              by day.
            </p>

            <div className={styles.companies}>
              <img src="/company_logos/haven.svg" />
              <img src="/company_logos/gymshark.svg" />
              <img src="/company_logos/mojo.svg" />
              <img src="/company_logos/and.svg" />
              <img src="/company_logos/sorted.svg" />
              <img src="/company_logos/cf247.svg" />
            </div>
          </div>
        </div>
        <Grid>
          <div className={styles.blockSpacing}>
            <h2>ABOUT</h2>
            <p>
              I'm a self taught front end developer based in Manchester, UK. I
              work building digital products for both businesses and consumer
              use. I'm confident, naturally curious, and improving on my skills
              day by day.
            </p>
            <p>
              Outside of work life and parenting life I like to lift heavy and
              play games. More specifically Olympic Lifting & CrossFit, I
              promise I wont talk about CrossFit all the time. When it comes to
              games HMU for League of Legends and Cod any day of the week.
            </p>
            <Link className={styles.styledLink} href="/about">
              About me
            </Link>
          </div>
        </Grid>
        <Grid>
          <div className={styles.blockSpacing}>
            <h2>Blog</h2>
            <p>
              My mad ramblings about the world of web development, tech and
              other things I find vaguely interesting. I also cross post my blog
              posts to{" "}
              <a
                href="https://dev.to/kieranmv95"
                target="_blank"
                rel="noreferrer"
              >
                dev.to
              </a>
            </p>
            <Link className={styles.styledLink} href="/blog">
              Blog
            </Link>
          </div>
        </Grid>
        <Grid>
          <div className={styles.blockSpacing} id="contact">
            <h2>Contact</h2>
            <p>
              I used to have my email here. But I&apos;m sick of having people
              message me asking to fix their printers &amp; phones.
            </p>
            <p>
              Hit me up on LinkedIn if you want me, I promise to get back
              quickly
            </p>
            <Link className={styles.styledLink} href="/">
              LinkedIn
            </Link>
          </div>
        </Grid>
        <Footer />
        <Social />
      </main>
    </>
  );
}
